# On every push this script is executed
on: push
name: Build and deploy blog to github pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: blog
          CHECK_LINKS: true
          # Provide personal access token
          #TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
